services:
  extracteur:
    build: .
    container_name: extracteur
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file: extracteur.env
    environment:
      STATUS_FILE: /app/data/status.json
      DB_FILE: /app/data/extracteur.db
    volumes:
      - ./data:/app/data
